### ISSUE TITLE
issues with setting up pre-commit

### ISSUE THREAD

**Issue by bbelderbos** [abaddonpuff/bladeART#7]
Tried to install pre-commit. but pyupgrade, black and isort all failed :/ after a bunch of troubleshooting. Help would be appreciated this is my error.

`isort....................................................................Failed
- hook id: isort
- files were modified by this hook

Skipped 1943 files
Fixing /Users/0xabaddon/repos/bladeART/blade/procData/Scripts/githubLogParser.py
Skipped 330 files

black....................................................................Failed
- hook id: black
- exit code: 1

Traceback (most recent call last):
  File "/Users/0xabaddon/.cache/pre-commit/repo13tlngv2/py_env-python3/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/Users/0xabaddon/.cache/pre-commit/repo13tlngv2/py_env-python3/lib/python3.10/site-packages/black/__init__.py", line 1129, in patched_main
    patch_click()
  File "/Users/0xabaddon/.cache/pre-commit/repo13tlngv2/py_env-python3/lib/python3.10/site-packages/black/__init__.py", line 1115, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/Users/0xabaddon/.cache/pre-commit/repo13tlngv2/py_env-python3/lib/python3.10/site-packages/click/__init__.py)
Traceback (most recent call last):
  File "/Users/0xabaddon/.cache/pre-commit/repo13tlngv2/py_env-python3/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/Users/0xabaddon/.cache/pre-commit/repo13tlngv2/py_env-python3/lib/python3.10/site-packages/black/__init__.py", line 1129, in patched_main
    patch_click()
  File "/Users/0xabaddon/.cache/pre-commit/repo13tlngv2/py_env-python3/lib/python3.10/site-packages/black/__init__.py", line 1115, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/Users/0xabaddon/.cache/pre-commit/repo13tlngv2/py_env-python3/lib/python3.10/site-packages/click/__init__.py)

pyupgrade................................................................Failed
- hook id: pyupgrade
- exit code: 1

Traceback (most recent call last):
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/bin/pyupgrade", line 5, in <module>
    from pyupgrade._main import main
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_main.py", line 30, in <module>
    from pyupgrade._data import FUNCS
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_data.py", line 126, in <module>
    _import_plugins()
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_data.py", line 123, in _import_plugins
    __import__(name, fromlist=['_trash'])
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_plugins/pep584.py", line 5, in <module>
    from tokenize_rt import List
ImportError: cannot import name 'List' from 'tokenize_rt' (/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/tokenize_rt.py)
Traceback (most recent call last):
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/bin/pyupgrade", line 5, in <module>
    from pyupgrade._main import main
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_main.py", line 30, in <module>
    from pyupgrade._data import FUNCS
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_data.py", line 126, in <module>
    _import_plugins()
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_data.py", line 123, in _import_plugins
    __import__(name, fromlist=['_trash'])
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_plugins/pep584.py", line 5, in <module>
    from tokenize_rt import List
ImportError: cannot import name 'List' from 'tokenize_rt' (/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/tokenize_rt.py)
Traceback (most recent call last):
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/bin/pyupgrade", line 5, in <module>
    from pyupgrade._main import main
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_main.py", line 30, in <module>
    from pyupgrade._data import FUNCS
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_data.py", line 126, in <module>
    _import_plugins()
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_data.py", line 123, in _import_plugins
    __import__(name, fromlist=['_trash'])
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_plugins/pep584.py", line 5, in <module>
    from tokenize_rt import List
ImportError: cannot import name 'List' from 'tokenize_rt' (/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/tokenize_rt.py)
Traceback (most recent call last):
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/bin/pyupgrade", line 5, in <module>
    from pyupgrade._main import main
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_main.py", line 30, in <module>
    from pyupgrade._data import FUNCS
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_data.py", line 126, in <module>
    _import_plugins()
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_data.py", line 123, in _import_plugins
    __import__(name, fromlist=['_trash'])
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_plugins/pep584.py", line 5, in <module>
    from tokenize_rt import List
ImportError: cannot import name 'List' from 'tokenize_rt' (/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/tokenize_rt.py)
Traceback (most recent call last):
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/bin/pyupgrade", line 5, in <module>
    from pyupgrade._main import main
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_main.py", line 30, in <module>
    from pyupgrade._data import FUNCS
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_data.py", line 126, in <module>
    _import_plugins()
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_data.py", line 123, in _import_plugins
    __import__(name, fromlist=['_trash'])
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_plugins/pep584.py", line 5, in <module>
    from tokenize_rt import List
ImportError: cannot import name 'List' from 'tokenize_rt' (/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/tokenize_rt.py)
Traceback (most recent call last):
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/bin/pyupgrade", line 5, in <module>
    from pyupgrade._main import main
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_main.py", line 30, in <module>
    from pyupgrade._data import FUNCS
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_data.py", line 126, in <module>
    _import_plugins()
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_data.py", line 123, in _import_plugins
    __import__(name, fromlist=['_trash'])
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_plugins/pep584.py", line 5, in <module>
    from tokenize_rt import List
ImportError: cannot import name 'List' from 'tokenize_rt' (/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/tokenize_rt.py)
Traceback (most recent call last):
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/bin/pyupgrade", line 5, in <module>
    from pyupgrade._main import main
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_main.py", line 30, in <module>
    from pyupgrade._data import FUNCS
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_data.py", line 126, in <module>
    _import_plugins()
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_data.py", line 123, in _import_plugins
    __import__(name, fromlist=['_trash'])
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_plugins/pep584.py", line 5, in <module>
    from tokenize_rt import List
ImportError: cannot import name 'List' from 'tokenize_rt' (/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/tokenize_rt.py)
Traceback (most recent call last):
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/bin/pyupgrade", line 5, in <module>
    from pyupgrade._main import main
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_main.py", line 30, in <module>
    from pyupgrade._data import FUNCS
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_data.py", line 126, in <module>
    _import_plugins()
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_data.py", line 123, in _import_plugins
    __import__(name, fromlist=['_trash'])
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_plugins/pep584.py", line 5, in <module>
    from tokenize_rt import List
ImportError: cannot import name 'List' from 'tokenize_rt' (/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/tokenize_rt.py)
Traceback (most recent call last):
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/bin/pyupgrade", line 5, in <module>
    from pyupgrade._main import main
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_main.py", line 30, in <module>
    from pyupgrade._data import FUNCS
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_data.py", line 126, in <module>
    _import_plugins()
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_data.py", line 123, in _import_plugins
    __import__(name, fromlist=['_trash'])
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_plugins/pep584.py", line 5, in <module>
    from tokenize_rt import List
ImportError: cannot import name 'List' from 'tokenize_rt' (/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/tokenize_rt.py)
Traceback (most recent call last):
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/bin/pyupgrade", line 5, in <module>
    from pyupgrade._main import main
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_main.py", line 30, in <module>
    from pyupgrade._data import FUNCS
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_data.py", line 126, in <module>
    _import_plugins()
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_data.py", line 123, in _import_plugins
    __import__(name, fromlist=['_trash'])
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_plugins/pep584.py", line 5, in <module>
    from tokenize_rt import List
ImportError: cannot import name 'List' from 'tokenize_rt' (/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/tokenize_rt.py)
Traceback (most recent call last):
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/bin/pyupgrade", line 5, in <module>
    from pyupgrade._main import main
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_main.py", line 30, in <module>
    from pyupgrade._data import FUNCS
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_data.py", line 126, in <module>
    _import_plugins()
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_data.py", line 123, in _import_plugins
    __import__(name, fromlist=['_trash'])
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_plugins/pep584.py", line 5, in <module>
    from tokenize_rt import List
ImportError: cannot import name 'List' from 'tokenize_rt' (/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/tokenize_rt.py)
Traceback (most recent call last):
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/bin/pyupgrade", line 5, in <module>
    from pyupgrade._main import main
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_main.py", line 30, in <module>
    from pyupgrade._data import FUNCS
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_data.py", line 126, in <module>
    _import_plugins()
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_data.py", line 123, in _import_plugins
    __import__(name, fromlist=['_trash'])
  File "/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/pyupgrade/_plugins/pep584.py", line 5, in <module>
    from tokenize_rt import List
ImportError: cannot import name 'List' from 'tokenize_rt' (/Users/0xabaddon/.cache/pre-commit/repozjlijubm/py_env-python3/lib/python3.10/site-packages/tokenize_rt.py)`

_Originally posted by @abaddonpuff in https://github.com/abaddonpuff/bladeART/pull/4#discussion_r1582012425_

**Comment by bbelderbos** [comment]
@abaddonpuff what are the steps you followed?

For me:

```
pip install pre-commit
# added .pre-commit-config.yaml from gist
pre-commit install
pre-commit autoupdate
pre-commit run --all-files
```

After this command I only see linter violations highlighted in the project files, nothing from venv:

<img width="1582" alt="image" src="https://github.com/abaddonpuff/bladeART/assets/387927/3468d81a-7442-4cd1-b801-3e7c1506b6f2">

<img width="1582" alt="image" src="https://github.com/abaddonpuff/bladeART/assets/387927/37b1b185-89f6-40c9-a363-121eade0267b">

**Comment by abaddonpuff** [comment]
It works after the above steps, I was just following the steps from the video.

**Comment by bbelderbos** [comment]
Ok cool, adds quite some noise for now so happy we left it. You can also run black manually once to clean up, and same for flask, things like cleaning up unused imports or non explicit exception handling the latter highlights are quite useful. But less of a prio right now.

**Comment by abaddonpuff** [comment]
Do you have an intro tutorial or source for Black? I only remember using it on PyBites bites haha

**Comment by bbelderbos** [comment]
Not really, you can just pip install it, I actually have it "globally" installed using:

Pipx: Access Python Utilities Anywhere, No Virtual Environment Required
https://www.youtube.com/watch?v=xvCShK1Bqxk

A more popular tool is ruff though because it's built with Rust so it's blazingly fast, so you might want to install and run that one. Not much of a guide needed, it's literally just install and run :)

Let me know if it works for you ...
